[project]
name = "altinn-app-explore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "httpx>=0.28.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
]

[tool.black]
line-length = 120
