{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "d274941d-c734-4b0f-aa97-09dfb66520d2",
   "metadata": {},
   "source": [
    "## Missing icu-data-full when using DisplayFooter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0d4364d-fccc-451c-8f4d-2899f711bc26",
   "metadata": {},
   "outputs": [],
   "source": [
    "# RUN apk add --no-cache icu-libs icu-data-full tzdata\n",
    "with Apps.init() as apps:\n",
    "    apps.where(\n",
    "        lambda app: app.dockerfile.find(r\"RUN apk add.*icu-libs\") != None\n",
    "        and app.dockerfile.find(r\"RUN apk add.*icu-data-full\") == None\n",
    "        and app.app_settings.some(lambda app_settings: app_settings[\".PdfGeneratorSettings.DisplayFooter\"] == True)\n",
    "    ).select(\n",
    "        {\n",
    "            \"Dockerfile\": lambda app: app.dockerfile.find(r\"RUN apk add.+icu-libs\"),\n",
    "            \"PdfGeneratorSettings\": lambda app: str(\n",
    "                app.app_settings.filter(\n",
    "                    lambda app_settings: app_settings[\".PdfGeneratorSettings.DisplayFooter\"] == True\n",
    "                )\n",
    "                .map(lambda app_settings: app_settings[\".PdfGeneratorSettings\"])\n",
    "                .first\n",
    "            ),\n",
    "        }\n",
    "    ).order_by(\n",
    "        lambda app: (app.org, app.app, app.env)\n",
    "    ).table()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec7a4d70-3872-4e2e-8c6f-9d147a4f4586",
   "metadata": {},
   "outputs": [],
   "source": [
    "with Apps.init() as apps:\n",
    "    apps.where(lambda app: app.dockerfile.find(r\"RUN apk add.*icu-libs\") != None).table()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "86044d73-721b-4b46-8858-aa566afb8e3e",
   "metadata": {},
   "outputs": [],
   "source": [
    "with Apps.init() as apps:\n",
    "    apps.select({\"TimeZoneInfo\": lambda app: app.cs.flat_map(lambda cs: cs.identifiers(name=\"TimeZoneInfo\"))}).where(\n",
    "        lambda app: len(app[\"TimeZoneInfo\"]) > 0\n",
    "    ).table()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
